export const DATA = [
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
    title: "First Item",
    creator: "Creator Name",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    thubmnail: "https://reactnative.dev/img/tiny_logo.png",
    stats: "6.4M views 4 days ago",
    duration: "6:37",
    videoLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    likes: 400,
    dislikes: 2,
    views: 40000,
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
    title: "Second Item",
    creator: "Creator Name",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    thubmnail: "https://reactnative.dev/img/tiny_logo.png",
    stats: "6.4M views 4 days ago",
    duration: "6:37",
    videoLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    likes: 400,
    dislikes: 2,
    views: 40000,
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e29d72",
    title: "Third Item",
    creator: "Creator Name",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    thubmnail: "https://reactnative.dev/img/tiny_logo.png",
    stats: "6.4M views 4 days ago",
    duration: "6:37",
    videoLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    likes: 400,
    dislikes: 2,
    views: 40000,
  },
  {
    id: "bd7acbea-c1b1-46c2-aed5-3ad53ab28ba",
    title: "First Item",
    creator: "Creator Name",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    thubmnail: "https://reactnative.dev/img/tiny_logo.png",
    stats: "6.4M views 4 days ago",
    duration: "6:37",
    videoLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    likes: 400,
    dislikes: 2,
    views: 40000,
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91a97f63",
    title: "Second Item",
    creator: "Creator Name",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    thubmnail: "https://reactnative.dev/img/tiny_logo.png",
    stats: "6.4M views 4 days ago",
    duration: "6:37",
    videoLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    likes: 400,
    dislikes: 2,
    views: 40000,
  },
  {
    id: "58694a0f-3da1-471f-bd96-14557129d72",
    title: "Third Item",
    creator: "Creator Name",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    thubmnail: "https://reactnative.dev/img/tiny_logo.png",
    stats: "6.4M views 4 days ago",
    duration: "6:37",
    videoLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    likes: 400,
    dislikes: 2,
    views: 40000,
  },
];
